#version: '2'  
services:
  demoauth.rutoken.ru-prod:
    container_name: ${APP_CONTAINER_NAME}
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    network_mode: "shared"
    restart: always
    volumes:
      - ${APP_FOLDER}:/app
    expose:
      - ${APP_OUT_PORT}
    command: sh -c "apt update && cd /app && dotnet RutokenTotpFido2Demo.dll --urls='http://0.0.0.0:${APP_OUT_PORT}' "
    links:
      - demoauth.rutoken.ru-psql
  demoauth.rutoken.ru-psql:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres
    network_mode: "shared"
    environment:
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data
    expose:
      - ${DB_PORT}
